// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHanvn09kT_LdLfdZoqzcXULgbNM7BLZI',
    appId: '1:23401957871:web:803124097e3a7f365fce1a',
    messagingSenderId: '23401957871',
    projectId: 'mikhunchik-49677',
    authDomain: 'mikhunchik-49677.firebaseapp.com',
    storageBucket: 'mikhunchik-49677.firebasestorage.app',
    measurementId: 'G-KH6ER5E5HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslchlM0qN2HfTMsEFLMC2rCQWPrvj44s',
    appId: '1:23401957871:android:bb0c1c05a377aa705fce1a',
    messagingSenderId: '23401957871',
    projectId: 'mikhunchik-49677',
    storageBucket: 'mikhunchik-49677.firebasestorage.app',
  );
}
